# Generated by Django 6.1 on 2026-08-16 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0011_remove_bookingreference_unique_booking_reference_kind_and_more'),
        ('scheduling', '0011_eventtypehost_assignment_count_and_more'),
        ('teams', '0002_team_avatar_team_brand_colour_team_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_forms', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_forms', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], max_length=50)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('is_routing_field', models.BooleanField(default=True)),
                ('identifier', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='routing.routingform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('route_to_event_type', 'Route to Event Type'), ('route_to_member', 'Route to Member'), ('route_to_external_url', 'Route to External URL'), ('show_message', 'Show Message')], max_length=50)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_fallback', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='routing.routingform')),
                ('target_event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.eventtype')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoutingFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_response', to='bookings.booking')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='routing.routingform')),
                ('routed_to_event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.eventtype')),
                ('routed_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='routing.routingrule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='routingform',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_owner_routing_form_slug'),
        ),
        migrations.AddConstraint(
            model_name='routingform',
            constraint=models.UniqueConstraint(fields=('team', 'slug'), name='unique_team_routing_form_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='routingformfield',
            unique_together={('form', 'identifier')},
        ),
    ]
