repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: django-migrations
        name: Check Django Migrations
        entry: bash -c '.venv/bin/python manage.py makemigrations --check --dry-run'
        language: system
        types: [python]
        pass_filenames: false
