# Generated by Django 6.1 on 2026-08-11 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.integrations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("microsoft", "Microsoft"),
                            ("caldav", "CalDAV"),
                            ("apple", "Apple"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "external_account_email",
                    models.EmailField(
                        help_text="The email address of the connected account", max_length=254
                    ),
                ),
                (
                    "external_account_id",
                    models.CharField(
                        help_text="The stable provider account identifier", max_length=255
                    ),
                ),
                (
                    "access_token",
                    apps.integrations.models.DedicatedKeyEncryptedTextField(blank=True, null=True),
                ),
                (
                    "refresh_token",
                    apps.integrations.models.DedicatedKeyEncryptedTextField(blank=True, null=True),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scopes",
                    models.JSONField(blank=True, default=list, help_text="List of granted scopes"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider", "external_account_id"),
                        name="unique_user_provider_account",
                    )
                ],
            },
        ),
    ]
