# Generated by Django 6.1 on 2026-08-11 17:37

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_notificationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectedCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_calendar_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("background_color", models.CharField(blank=True, max_length=50)),
                ("is_busy_source", models.BooleanField(default=True)),
                ("is_write_target", models.BooleanField(default=False)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to="integrations.calendarconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusyBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ("external_event_id", models.CharField(max_length=255)),
                ("is_all_day", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.calendarconnection",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.selectedcalendar",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="selectedcalendar",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_calendar_id"), name="unique_connection_calendar"
            ),
        ),
        migrations.AddIndex(
            model_name="busyblock",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["period"], name="busyblock_period_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="busyblock",
            index=models.Index(
                fields=["connection", "period"], name="integration_connect_7a4909_idx"
            ),
        ),
    ]
