# Generated by Django 6.1 on 2026-08-11 18:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_selectedcalendar_busyblock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectedcalendar",
            name="sync_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="WatchChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("resource_id", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_channels",
                        to="integrations.selectedcalendar",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_channels",
                        to="integrations.calendarconnection",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "calendar"), name="unique_watch_channel_per_calendar"
                    )
                ],
            },
        ),
    ]
