# Generated by Django 6.1 on 2026-08-11 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.integrations.models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0004_selectedcalendar_sync_token_watchchannel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("zoom", "Zoom"), ("google_meet", "Google Meet")], max_length=50
                    ),
                ),
                ("external_account_email", models.EmailField(max_length=254)),
                ("external_account_id", models.CharField(max_length=255)),
                (
                    "access_token",
                    apps.integrations.models.DedicatedKeyEncryptedTextField(blank=True, null=True),
                ),
                (
                    "refresh_token",
                    apps.integrations.models.DedicatedKeyEncryptedTextField(blank=True, null=True),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider", "external_account_id"),
                        name="unique_conference_user_provider_account",
                    )
                ],
            },
        ),
    ]
