# Generated by Django 6.1 on 2026-08-16 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_conferenceconnection'),
        ('teams', '0002_team_avatar_team_brand_colour_team_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarconnection',
            name='unique_user_provider_account',
        ),
        migrations.RemoveConstraint(
            model_name='conferenceconnection',
            name='unique_conference_user_provider_account',
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='conferenceconnection',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='calendarconnection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conferenceconnection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='calendarconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'provider', 'external_account_id'), name='unique_user_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='calendarconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'provider', 'external_account_id'), name='unique_team_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='calendarconnection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='calendar_connection_user_or_team'),
        ),
        migrations.AddConstraint(
            model_name='conferenceconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'provider', 'external_account_id'), name='unique_conference_user_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='conferenceconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'provider', 'external_account_id'), name='unique_conference_team_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='conferenceconnection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='conference_connection_user_or_team'),
        ),
    ]
