# Generated by Django 6.1 on 2026-08-11 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_booking_sync_status_bookingreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe_connect', max_length=30)),
                ('external_account_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('details_submitted', models.BooleanField(default=False)),
                ('requirements_due', models.JSONField(blank=True, default=list)),
                ('default_currency', models.CharField(blank=True, max_length=3)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=30)),
                ('external_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('external_charge_id', models.CharField(blank=True, max_length=255)),
                ('fee_percent_applied', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fee_fixed_applied', models.PositiveIntegerField(default=0)),
                ('fee_amount_cents', models.PositiveIntegerField(default=0)),
                ('refund_amount_cents', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('local_state', models.JSONField(default=dict)),
                ('remote_state', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_flags', to='payments.payment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlotHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_hold', to='bookings.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_holds', to='payments.payment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_payment_account_per_user_provider'),
        ),
    ]
