# Generated by Django 6.1 on 2026-08-12 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_gateway_fee_cents_payment_net_owed_cents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostledger',
            name='entry_type',
            field=models.CharField(choices=[('charge', 'Charge'), ('service_fee', 'Service Fee'), ('platform_fee', 'Platform Fee'), ('gateway_fee', 'Gateway Fee'), ('refund', 'Refund'), ('refund_fee_reversal', 'Fee Reversal'), ('payout', 'Payout'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='HostPaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms_accepted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'terms_version'), name='unique_host_terms_version')],
            },
        ),
    ]
