# Generated by Django 6.1 on 2026-08-12 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_hostledger_entry_type_hostpaymentterms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('total_ledger_cents', models.IntegerField()),
                ('expected_merchant_hold_cents', models.IntegerField()),
                ('difference_cents', models.IntegerField()),
                ('is_clean', models.BooleanField()),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-reconciled_at'],
            },
        ),
        migrations.AddField(
            model_name='hostledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostledger',
            name='entry_type',
            field=models.CharField(choices=[('charge', 'Charge'), ('service_fee', 'Service Fee'), ('platform_fee', 'Platform Fee'), ('gateway_fee', 'Gateway Fee'), ('refund', 'Refund'), ('refund_fee_reversal', 'Fee Reversal'), ('payout', 'Payout'), ('payout_reversal', 'Payout Reversal'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank_transfer', 'Bank Transfer')], max_length=30)),
                ('account_name', models.CharField(max_length=100)),
                ('encrypted_account_details', models.TextField()),
                ('is_verified', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='payments.payoutmethod')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='hostledger',
            name='payout_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payoutrequest'),
        ),
    ]
