# Generated by Django 6.1 on 2026-08-12 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_hostledger_provider_is_custodial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStripeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', apps.integrations.models.DedicatedKeyEncryptedTextField(blank=True, null=True)),
                ('publishable_key', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', apps.integrations.models.DedicatedKeyEncryptedTextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
