# Generated by Django 6.1 on 2026-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_platformstripesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostledger',
            name='is_custodial',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
