# Generated by Django 6.1 on 2026-08-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_hostledger_is_custodial'),
        ('teams', '0002_team_avatar_team_brand_colour_team_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hostpaymentterms',
            name='unique_host_terms_version',
        ),
        migrations.RemoveConstraint(
            model_name='paymentaccount',
            name='unique_payment_account_per_user_provider',
        ),
        migrations.AddField(
            model_name='hostledger',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='teams.team'),
        ),
        migrations.AddField(
            model_name='hostpaymentterms',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms_accepted', to='teams.team'),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='teams.team'),
        ),
        migrations.AddField(
            model_name='payout',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='teams.team'),
        ),
        migrations.AddField(
            model_name='payoutmethod',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='teams.team'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='hostledger',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostpaymentterms',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payout',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutmethod',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='hostledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='host_ledger_host_or_team'),
        ),
        migrations.AddConstraint(
            model_name='hostpaymentterms',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('user', 'terms_version'), name='unique_host_terms_version'),
        ),
        migrations.AddConstraint(
            model_name='hostpaymentterms',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('team', 'terms_version'), name='unique_team_terms_version'),
        ),
        migrations.AddConstraint(
            model_name='hostpaymentterms',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='payment_terms_host_or_team'),
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('user', 'provider'), name='unique_payment_account_per_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('team', 'provider'), name='unique_payment_account_per_team_provider'),
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='payment_account_user_or_team'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='payout_host_or_team'),
        ),
        migrations.AddConstraint(
            model_name='payoutmethod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='payout_method_host_or_team'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='payout_request_host_or_team'),
        ),
    ]
