# Generated by Django 6.1 on 2026-08-11 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('slot_interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0)),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0)),
                ('minimum_notice_minutes', models.PositiveIntegerField(default=0)),
                ('window_type', models.CharField(choices=[('rolling', 'Rolling'), ('fixed_range', 'Fixed Range'), ('indefinite', 'Indefinite')], default='rolling', max_length=30)),
                ('rolling_days', models.PositiveIntegerField(default=60)),
                ('rolling_business_days_only', models.BooleanField(default=False)),
                ('range_start', models.DateField(blank=True, null=True)),
                ('range_end', models.DateField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('ms_teams', 'MS Teams'), ('phone_host_calls', 'Phone (Host calls invitee)'), ('phone_invitee_calls', 'Phone (Invitee calls host)'), ('in_person', 'In Person'), ('custom_link', 'Custom Link'), ('ask_invitee', 'Ask Invitee')], default='google_meet', max_length=30)),
                ('location_value', models.CharField(blank=True, max_length=500)),
                ('max_bookings_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('max_bookings_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('max_bookings_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('seats_per_slot', models.PositiveIntegerField(default=1)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_guests', models.BooleanField(default=True)),
                ('allow_rescheduling', models.BooleanField(default=True)),
                ('allow_cancellation', models.BooleanField(default=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('assignment_strategy', models.CharField(choices=[('single', 'Single'), ('collective', 'Collective'), ('round_robin', 'Round Robin')], default='single', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.schedule')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='BookingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('phone', 'Phone'), ('email', 'Email'), ('url', 'URL')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scheduling.eventtype')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_event_type_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 1440)), name='event_type_valid_duration'),
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rolling_days__isnull', False), ('window_type', 'rolling')), models.Q(('range_end__isnull', False), ('range_start__isnull', False), ('window_type', 'fixed_range')), ('window_type', 'indefinite'), _connector='OR'), name='event_type_valid_window'),
        ),
    ]
