# Generated by Django 6.1

from django.db import migrations


def create_default_event_types(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    EventType = apps.get_model("scheduling", "EventType")

    event_types = []
    for user in User.objects.all():
        # Using default values specified in the model
        event_types.append(
            EventType(
                owner=user,
                slug="30-minute-meeting",
                title="30 Minute Meeting",
                duration_minutes=30,
                description="A 30 minute meeting.",
                window_type="rolling",
                rolling_days=60,
                rolling_business_days_only=False,
                location_type="google_meet",
                seats_per_slot=1,
                requires_confirmation=False,
                is_hidden=False,
                is_active=True,
                allow_guests=True,
                allow_rescheduling=True,
                allow_cancellation=True,
                price_cents=0,
                currency="USD",
                assignment_strategy="single",
            )
        )

    EventType.objects.bulk_create(event_types)


def reverse_default_event_types(apps, schema_editor):
    EventType = apps.get_model("scheduling", "EventType")
    EventType.objects.filter(slug="30-minute-meeting", title="30 Minute Meeting").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_eventtype_bookingquestion_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_event_types, reverse_default_event_types),
    ]
