# Generated by Django 6.1 on 2026-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_eventtype_confirmation_deadline_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='location_type',
            field=models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('ms_teams', 'MS Teams'), ('jitsi', 'Jitsi'), ('phone_host_calls', 'Phone (Host calls invitee)'), ('phone_invitee_calls', 'Phone (Invitee calls host)'), ('in_person', 'In Person'), ('custom_link', 'Custom Link'), ('ask_invitee', 'Ask Invitee')], default='google_meet', max_length=30),
        ),
    ]
