# Generated by Django 6.1 on 2026-08-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_eventtype_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='waitlist_claim_window_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='waitlist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='waitlist_max_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
