# Generated by Django 6.1 on 2026-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_eventtypehost'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtypehost',
            name='assignment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventtypehost',
            name='buffer_after_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventtypehost',
            name='buffer_before_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventtypehost',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventtypehost',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtypehost',
            name='outside_working_hours_count',
            field=models.IntegerField(default=0),
        ),
    ]
