# Generated by Django 6.1 on 2026-08-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_eventtypehost'),
        ('teams', '0002_team_avatar_team_brand_colour_team_description_and_more'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('team__isnull', True)), models.Q(('owner__isnull', True), ('team__isnull', False)), _connector='OR'), name='workflow_owner_or_team'),
        ),
    ]
