# Generated by Django 6.1 on 2026-08-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('teams', '0002_team_avatar_team_brand_colour_team_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_host_email',
        ),
        migrations.RemoveConstraint(
            model_name='clienttag',
            name='unique_client_tag_host_name',
        ),
        migrations.AddField(
            model_name='client',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='teams.team'),
        ),
        migrations.AddField(
            model_name='clienttag',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_tags', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='client',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clienttag',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['team', 'email'], name='clients_cli_team_id_f6d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['team', 'last_seen_at'], name='clients_cli_team_id_bf70db_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('host', 'email'), name='unique_client_host_email'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('host__isnull', True)), fields=('team', 'email'), name='unique_client_team_email'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='client_host_or_team'),
        ),
        migrations.AddConstraint(
            model_name='clienttag',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('host', 'name'), name='unique_client_tag_host_name'),
        ),
        migrations.AddConstraint(
            model_name='clienttag',
            constraint=models.UniqueConstraint(condition=models.Q(('host__isnull', True)), fields=('team', 'name'), name='unique_client_tag_team_name'),
        ),
        migrations.AddConstraint(
            model_name='clienttag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='client_tag_host_or_team'),
        ),
    ]
