# Generated by Django 6.1 on 2026-08-11 09:40

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_btree_gist'),
        ('scheduling', '0003_create_default_event_types'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('buffered_period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('invitee_timezone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('invitee_name', models.CharField(max_length=150)),
                ('invitee_email', models.EmailField(db_index=True, max_length=254)),
                ('invitee_notes', models.TextField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('location_type', models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('ms_teams', 'MS Teams'), ('phone_host_calls', 'Phone (Host calls invitee)'), ('phone_invitee_calls', 'Phone (Invitee calls host)'), ('in_person', 'In Person'), ('custom_link', 'Custom Link'), ('ask_invitee', 'Ask Invitee')], max_length=30)),
                ('location_value', models.CharField(blank=True, max_length=500)),
                ('meeting_url', models.URLField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('host', 'Host'), ('invitee', 'Invitee'), ('system', 'System')], max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.eventtype')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_bookings', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='bookings.booking')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_organizer', models.BooleanField(default=False)),
                ('response_status', models.CharField(blank=True, max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['host', 'start_at'], name='bookings_bo_host_id_227563_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='booking_end_time_gt_start_time'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('pending', 'pending_payment', 'confirmed'))), expressions=[('host', '='), ('buffered_period', '&&')], name='no_overlapping_bookings_per_host'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('booking', 'kind'), name='unique_notification_kind_per_booking'),
        ),
    ]
