# Generated by Django 6.1 on 2026-08-16 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_sync_status_bookingreference'),
        ('scheduling', '0009_eventtype_waitlist_claim_window_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_name', models.CharField(max_length=150)),
                ('invitee_email', models.EmailField(db_index=True, max_length=254)),
                ('invitee_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('invitee_timezone', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('preferred_dates', models.JSONField(blank=True, default=list)),
                ('preferred_time_ranges', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('offered', 'Offered'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('removed', 'Removed')], default='waiting', max_length=20)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('offered_booking_slot', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='scheduling.eventtype')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'status', 'created_at'], name='bookings_wa_event_t_e80734_idx')],
            },
        ),
    ]
