# Generated by Django 6.1 on 2026-08-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_waitlistentry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationlog',
            name='unique_notification_kind_per_booking',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='waitlist_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.waitlistentry'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking', 'kind'), name='unique_notification_kind_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('waitlist_entry__isnull', False)), fields=('waitlist_entry', 'kind'), name='unique_notification_kind_per_waitlist_entry'),
        ),
    ]
