# Generated by Django 6.1 on 2026-08-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_notificationlog_unique_notification_kind_per_booking_and_more'),
        ('clients', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clients.client'),
        ),
    ]
