# Generated by Django on 2026-08-16 11:00

from django.db import migrations


def backfill_clients(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    Client = apps.get_model('clients', 'Client')
    
    # Process bookings
    # It might be slow for huge DBs, but sufficient for this data migration
    for booking in Booking.objects.iterator():
        email = booking.invitee_email.lower().strip()
        client, created = Client.objects.get_or_create(
            host=booking.host,
            email=email,
            defaults={
                'name': booking.invitee_name,
                'first_seen_at': booking.created_at,
                'last_seen_at': booking.start_at,
                'timezone': booking.invitee_timezone,
                'source': 'backfill',
            }
        )
        if not created:
            update_fields = []
            if booking.invitee_name and booking.invitee_name != client.name:
                if booking.invitee_name not in client.known_names:
                    client.known_names.append(booking.invitee_name)
                    update_fields.append('known_names')
            if booking.start_at > client.last_seen_at:
                client.last_seen_at = booking.start_at
                update_fields.append('last_seen_at')
            if update_fields:
                client.save(update_fields=update_fields)
                
        booking.client = client
        booking.save(update_fields=['client'])

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_booking_client_id_booking_client'),
    ]

    operations = [
        migrations.RunPython(backfill_clients, migrations.RunPython.noop),
    ]
