# Generated by Django 6.1 on 2026-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_backfill_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
