# Generated by Django 6.1 on 2026-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_metadata'),
        ('integrations', '0006_remove_calendarconnection_unique_user_provider_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingreference',
            name='unique_booking_reference_kind',
        ),
        migrations.AddConstraint(
            model_name='bookingreference',
            constraint=models.UniqueConstraint(fields=('booking', 'kind', 'connection'), name='unique_booking_reference_kind'),
        ),
    ]
