# Generated by Django 6.1 on 2026-08-16 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('scheduling', '0009_eventtype_waitlist_claim_window_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('step', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='scheduling.eventtype')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('bookings_created', models.PositiveIntegerField(default=0)),
                ('bookings_cancelled', models.PositiveIntegerField(default=0)),
                ('bookings_rescheduled', models.PositiveIntegerField(default=0)),
                ('bookings_completed', models.PositiveIntegerField(default=0)),
                ('no_shows', models.PositiveIntegerField(default=0)),
                ('revenue_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('profile_viewed_count', models.PositiveIntegerField(default=0)),
                ('booking_page_viewed_count', models.PositiveIntegerField(default=0)),
                ('date_selected_count', models.PositiveIntegerField(default=0)),
                ('slot_selected_count', models.PositiveIntegerField(default=0)),
                ('form_started_count', models.PositiveIntegerField(default=0)),
                ('form_submitted_count', models.PositiveIntegerField(default=0)),
                ('payment_started_count', models.PositiveIntegerField(default=0)),
                ('booking_completed_count', models.PositiveIntegerField(default=0)),
                ('booking_abandoned_count', models.PositiveIntegerField(default=0)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='scheduling.eventtype')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.AddIndex(
            model_name='bookingfunnelevent',
            index=models.Index(fields=['host', 'timestamp'], name='analytics_b_host_id_ed0a42_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingfunnelevent',
            index=models.Index(fields=['session_id', 'step'], name='analytics_b_session_05d6a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetric',
            unique_together={('host', 'event_type', 'date', 'currency')},
        ),
    ]
