# Generated by Django 6.1 on 2026-08-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bookingfunnelevent_dailymetric_delete_pageview_and_more'),
        ('scheduling', '0010_eventtypehost'),
        ('teams', '0002_team_avatar_team_brand_colour_team_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookingfunnelevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='teams.team'),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='bookingfunnelevent',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookingfunnelevent',
            index=models.Index(fields=['team', 'timestamp'], name='analytics_b_team_id_2fab11_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingfunnelevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='funnel_event_host_or_team'),
        ),
        migrations.AddConstraint(
            model_name='dailymetric',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('host', 'event_type', 'date', 'currency'), name='unique_daily_metric_host'),
        ),
        migrations.AddConstraint(
            model_name='dailymetric',
            constraint=models.UniqueConstraint(condition=models.Q(('host__isnull', True)), fields=('team', 'event_type', 'date', 'currency'), name='unique_daily_metric_team'),
        ),
        migrations.AddConstraint(
            model_name='dailymetric',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('team__isnull', True)), models.Q(('host__isnull', True), ('team__isnull', False)), _connector='OR'), name='daily_metric_host_or_team'),
        ),
    ]
